// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYxt2InlZsTTT3MjT1paRGHS2ghCQeKA',
    appId: '1:649229634613:web:24db4102cc5c04e265357c',
    messagingSenderId: '649229634613',
    projectId: 'livewell-apps',
    authDomain: 'livewell-apps.firebaseapp.com',
    storageBucket: 'livewell-apps.appspot.com',
    measurementId: 'G-LJC06T3P8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGPWBoAyXoiZPuOr1tVy_lhDbqiY6gVw',
    appId: '1:649229634613:android:e10c2d7c4ef6392265357c',
    messagingSenderId: '649229634613',
    projectId: 'livewell-apps',
    storageBucket: 'livewell-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxbnqu8icKNHauUZveyBjG5srd7f1GQIA',
    appId: '1:649229634613:ios:0e315444eb75a8d265357c',
    messagingSenderId: '649229634613',
    projectId: 'livewell-apps',
    storageBucket: 'livewell-apps.appspot.com',
    androidClientId: '649229634613-l8tqhjbf9o0lmu3mcs3ouhndi0aj5brk.apps.googleusercontent.com',
    iosClientId: '649229634613-k3rrdr47ps05uavsbggnvc70eabhv5tq.apps.googleusercontent.com',
    iosBundleId: 'com.livewellindo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxbnqu8icKNHauUZveyBjG5srd7f1GQIA',
    appId: '1:649229634613:ios:0e315444eb75a8d265357c',
    messagingSenderId: '649229634613',
    projectId: 'livewell-apps',
    storageBucket: 'livewell-apps.appspot.com',
    androidClientId: '649229634613-l8tqhjbf9o0lmu3mcs3ouhndi0aj5brk.apps.googleusercontent.com',
    iosClientId: '649229634613-k3rrdr47ps05uavsbggnvc70eabhv5tq.apps.googleusercontent.com',
    iosBundleId: 'com.livewellindo.app',
  );
}
