import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Welcome to Livewell': 'Welcome to Livewell',
          'Better Health Through Better Living':
              'Better Health Through Better Living',
          'Get Started': 'Get Started',
          'Sign In': 'Sign In',
          'Sign Up': 'Sign Up',
          'Already have account?': 'Already have account?',
          "Don't have account?": "Don't have account?",
          'Create New Account': 'Create New Account',
          'Enter your details to register': 'Enter your details to register',
          'Email Address': 'Email Address',
          'Password': 'Password',
          'Full Name': 'Full Name',
          'Or Sign up with': 'Or Sign up with',
          'First Name': 'First Name',
          'Last Name': 'Last Name',
          'or Sign in with': 'or Sign in with',
          'Forgot Password?': 'Forgot Password?',
          'Get Started!': 'Get Started!',
          'You are ready to go!': 'You are ready to go!',
          'Thanks for taking your time to create account with us. Let\'s start your wellness Journey':
              'Thanks for taking your time to create account with us. Let\'s start your wellness Journey',
          'Please enter your email address. You will receive a link to create a new password via email.':
              'Please enter your email address. You will receive a link to create a new password via email.',
          'Submit': 'Submit',
          'Forgot Password': 'Forgot Password',
          "by Sign in above, i agree to Livewell’s\n":
              "by Sign in above, i agree to Livewell’s\n",
          'Terms & Conditions ': 'Terms & Conditions ',
          'and ': 'and ',
          'Privacy Policy ': 'Privacy Policy ',
          'By signing up, I agree to Livewell’s \n':
              'By signing up, I agree to Livewell’s \n',
          'Done': 'Done',
          'Edit': 'Edit',
          'Save': 'Save',
          'Account Settings': 'Account Settings',
          'Daily Journal': 'Daily Journal',
          'Physical Information': 'Physical Information',
          'Exercise': 'Exercise',
          'My Goals': 'My Goals',
          'Logout': 'Logout',
          'Set Your Meal Time': 'Set Your Meal Time',
          'Breakfast': 'Breakfast',
          'Lunch': 'Lunch',
          'Dinner': 'Dinner',
          'Snack': 'Snack',
          'Diary': 'Diary',
          'Change Password': 'Change Password',
          'Update Weight': 'Update Weight',
          'Yes': 'Yes',
          'Your Recommended Foods': 'Your Recommended Foods',
          'Picked based on your nutritional needs':
              'Picked based on your nutritional needs',
          "Food Recommendation": "Food Recommendation",
          'Discover personalized food recommendations that match your nutritional needs. Filter franchise restaurants with ease and enjoy your meals to the fullest!':
              'Discover personalized food recommendations that match your nutritional needs. Filter franchise restaurants with ease and enjoy your meals to the fullest!',
          'No': 'No',
          'None': 'None',
          'Get Fitter': 'Get Fitter',
          'Better Sleeping': 'Better Sleeping',
          'Weight Loss': 'Weight Loss',
          'Track Nutrition': 'Track Nutrition',
          'Improve Overall Fitness': 'Improve Overall Fitness',
          'Scan a barcode': 'Scan a barcode',
          'Scan a meal': 'Scan a meal',
          'Scan Food': 'Scan Food',
          'Food Request Completed': 'Food Request Completed',
          'Thank You!': 'Thank You!',
          'Our team is working on your request.':
              'Our team is working on your request.',
          'Back To Dashboard': 'Back To Dashboard',
          'Nutrient Fact': 'Nutrient Fact',
          'Food': 'Food',
          'Add Food': 'Add Food',
          'Show nutrient facts': 'Show nutrient facts',
          'Serving Size': 'Serving Size',
          'Time': 'Time',
          'Cancel': 'Cancel',
          'Filter': 'Filter',
          'Reset Filter': 'Reset Filter',
          'Amount': 'Amount',
          "Number Of Serving": "Number Of Serving",
          'Calories': 'Calories',
          'Protein': 'Protein',
          'Carbs': 'Carbs',
          'Fat': 'Fat',
          'Male': 'Male',
          'Female': 'Female',
          'Save Changes': 'Save Changes',
          'Gender': 'Gender',
          'Age': 'Age',
          'Height (cm)': 'Height (cm)',
          'Weight (kg)': 'Weight (kg)',
          'Drink': 'Drink',
          'Dietary Restriction': 'Dietary Restriction',
          'Specific Goal': 'Specific Goal',
          'Sleep (Hours)': 'Sleep (Hours)',
          'Target Weight (kg)': 'Target Weight (kg)',
          'No results found': 'No results found',
          'NutriScore Details': 'NutriScore Details',
          'Enter Your OTP': 'Enter Your OTP',
          'Enter new password': 'Enter new password',
          'New Password': 'New Password',
          'Confirm Password': 'Confirm Password',
          'Change': 'Change',
          'Eating': 'Eating',
          'Search Result': 'Search Result',
          'Search here...': 'Search here...',
          'Today you have consumed ': 'Today you have consumed ',
          'of daily goals': 'of daily goals',
          'Add ': 'Add ',
          'Request Food': 'Request Food',
          'Food Name': 'Food Name',
          'Processing...': 'Processing...',
          'We’ll redirect you to another screen once we got the scanning result':
              'We’ll redirect you to another screen once we got the scanning result',
          'Exercise Information': 'Exercise Information',
          'Pre': 'Pre',
          'Next': 'Next',
          'Current Weight (Kg)': 'Current Weight (Kg)',
          'Update': 'Update',
          'Water Consumed': 'Water Consumed',
          'Custom': 'Custom',
          'Water Tracking': 'Water Tracking',
          'Add Drink': 'Add Drink',
          'See Details': 'See Details',
          'Low': 'Low',
          'Optimal': 'Optimal',
          'High': 'High',
          'Mid': 'Mid',
          'Below Target': 'Below Target',
          'On Track': 'On Track',
          'Excellent': 'Excellent',
          "Today’s Amount": "Today’s Amount",
          'Weekly Average': 'Weekly Average',
          'Last 7 days': 'Last 7 days',
          'Disclaimer': 'Disclaimer',
          'Your Value': 'Your Value',
          'Eaten': 'Eaten',
          'Burned': 'Burned',
          'Remaining': 'Remaining',
          'Task List': 'Task List',
          'Morning': 'Morning',
          'Afternoon': 'Afternoon',
          'Evening': 'Evening',
          'Keep with our plan, You are doing great!':
              'Keep with our plan, You are doing great!',
          'See My Progress': 'See My Progress',
          "You have reached ": "You have reached ",
          " of your goal!": " of your goal!",
          'Exercise habit': 'Exercise habit',
          "Daily Breakdown": "Daily Breakdown",
          'Poor': 'Poor',
          'Good': 'Good',
          'Almost': 'Almost',
          'Great': 'Great',
          'Goals Setting': 'Goals Setting',
          'Personal Information': 'Personal Information',
          'Request To Delete Account': 'Request To Delete Account',
          'Delete Account Permanently': 'Delete Account Permanently',
          'You account and content will be deleted permanently. You may cancel the deletion request by logging in your account within 30 days.':
              'You account and content will be deleted permanently. You may cancel the deletion request by logging in your account within 30 days.',
          "Your water intake for today ": "Your water intake for today ",
          'Livewell nutritional data is for general fitness and wellness use. May contain inaccuracies. Consult a professional for personalized advice.':
              'Livewell nutritional data is for general fitness and wellness use. May contain inaccuracies. Consult a professional for personalized advice.',
          'Let’s make today count, put your meal to track your progress':
              'Let’s make today count, put your meal to track your progress',
          'Don’t worry, We can definitely improve your nutrition together!':
              'Don’t worry, We can definitely improve your nutrition together!',
          'You’re doing great! Let’s make sure we push it a little further':
              'You’re doing great! Let’s make sure we push it a little further',
          'Great Job! Your nutrition is on point. Keep up the good work!':
              'Great Job! Your nutrition is on point. Keep up the good work!'
        },
        'es_ES': {
          'title': 'Hola',
        },
        'pt_BR': {
          'title': 'Olá',
        },
      };
}
